// Generated by gencpp from file gps_simulator/accelerometer_measurement.msg
// DO NOT EDIT!


#ifndef GPS_SIMULATOR_MESSAGE_GPS_MEASUREMENT_H
#define GPS_SIMULATOR_MESSAGE_GPS_MEASUREMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gps_simulator
{
template <class ContainerAllocator>
struct gps_measurement_
{
  typedef gps_measurement_<ContainerAllocator> Type;

  gps_measurement_()
    : x(0.0)
    , z(0.0)  {
    }
  gps_measurement_(const ContainerAllocator& _alloc)
    : x(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::gps_simulator::gps_measurement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gps_simulator::gps_measurement_<ContainerAllocator> const> ConstPtr;

}; // struct gps_measurement_

typedef ::gps_simulator::gps_measurement_<std::allocator<void> > gps_measurement;

typedef boost::shared_ptr< ::gps_simulator::gps_measurement > gps_measurementPtr;
typedef boost::shared_ptr< ::gps_simulator::gps_measurement const> gps_measurementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gps_simulator::gps_measurement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gps_simulator::gps_measurement_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gps_simulator::gps_measurement_<ContainerAllocator1> & lhs, const ::gps_simulator::gps_measurement_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gps_simulator::gps_measurement_<ContainerAllocator1> & lhs, const ::gps_simulator::gps_measurement_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gps_simulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gps_simulator::gps_measurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gps_simulator::gps_measurement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gps_simulator::gps_measurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gps_simulator::gps_measurement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps_simulator::gps_measurement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps_simulator::gps_measurement_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gps_simulator::gps_measurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d990ebeae1ee5ba6990ba82cc74e4c5";
  }

  static const char* value(const ::gps_simulator::gps_measurement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d990ebeae1ee5baULL;
  static const uint64_t static_value2 = 0x6990ba82cc74e4c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::gps_simulator::gps_measurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gps_simulator/gps_measurement";
  }

  static const char* value(const ::gps_simulator::gps_measurement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gps_simulator::gps_measurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 z\n"
;
  }

  static const char* value(const ::gps_simulator::gps_measurement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gps_simulator::gps_measurement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gps_measurement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gps_simulator::gps_measurement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gps_simulator::gps_measurement_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPS_SIMULATOR_MESSAGE_GPS_MEASUREMENT_H
